

export const APP_FEATURES = [
    {
        id:"01",
        title:"tailored just for you",
        description:"get interview questio  and model answer based on your role , experience and specific focus area"
    },
    {
        id:"02",
        title: "Learn at your Own pace",
        description:
        "Expand answer only when you are ready . dive deeper into any concept instantly with ai powered detailed concept"

    },

    {
        id: "03",
        title:" capture your insight",

        description:  "add personal notes to any questions and pin important one to the top - making you learning oore organiation"

    },
    {
        id:"04",
        title:'understand the " why" behind Answer ',
        description: " Beyond just answer - unlock detailed concept explanation generated by AI, helping you truly master each topic "
    },
    {
        id:"05",
        title:"Save , Organise, and Revisit",
        description: "easily Save your interview sets, Organise them nealtly in your dashBoard , and pick up preparation right where you left off"


    }


];
